// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2304ref0umCKE6zD4LOlcq-1eKEG_1X0',
    appId: '1:396409577713:web:9c3f221e5910c9f13e0950',
    messagingSenderId: '396409577713',
    projectId: 'tms-db-70579',
    authDomain: 'tms-db-70579.firebaseapp.com',
    storageBucket: 'tms-db-70579.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMnAydzTLgspz8LHrS0YQ4DtZldrMcU0',
    appId: '1:396409577713:android:b762172b9c9af36e3e0950',
    messagingSenderId: '396409577713',
    projectId: 'tms-db-70579',
    storageBucket: 'tms-db-70579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdZBenROykH39v7r70uOqRYayTVYMzvZg',
    appId: '1:396409577713:ios:4b10364df258b0833e0950',
    messagingSenderId: '396409577713',
    projectId: 'tms-db-70579',
    storageBucket: 'tms-db-70579.appspot.com',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdZBenROykH39v7r70uOqRYayTVYMzvZg',
    appId: '1:396409577713:ios:4b10364df258b0833e0950',
    messagingSenderId: '396409577713',
    projectId: 'tms-db-70579',
    storageBucket: 'tms-db-70579.appspot.com',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2304ref0umCKE6zD4LOlcq-1eKEG_1X0',
    appId: '1:396409577713:web:58f8a7b5f0677eb03e0950',
    messagingSenderId: '396409577713',
    projectId: 'tms-db-70579',
    authDomain: 'tms-db-70579.firebaseapp.com',
    storageBucket: 'tms-db-70579.appspot.com',
  );
}
